name: CI

on:
  push:
    branches: [ "main" ]
    # Publish semver tags as releases.
    tags: [ 'v*.*.*' ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: docker.io
  DOCKER_USERNAME: argentinaluiz
  IMAGE_NAME: argentinaluiz/docker-prod-test

jobs:
  ci:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ env.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Build for CI
        id: build-ci
        uses: docker/build-push-action@v5.0.0
        with:
          context: ./src/ci/nestjs-project
          file: ./src/ci/nestjs-project/Dockerfile.prod
          push: false
          load: true # driver docker-container
          target: ci
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:ci
          secrets: |
            github_token=${{ secrets.MY_GITHUB_TOKEN }}
          
